const translations = {
  pt: {
    'Início': 'Início', 'O Instituto': 'O Instituto', 'Projetos': 'Projetos', 'Transparência': 'Transparência',
    'Voluntariado': 'Voluntariado', 'Contato': 'Contato', 'Quero apoiar': 'Quero apoiar',
    'Instituto Kátia Carvalho': 'Instituto Kátia Carvalho', 'Impacto social': 'Impacto social',
    'Instituto Katia Carvalho': 'Instituto Kátia Carvalho', 'Instituto Katia Carvalho | Impacto que transforma': 'Instituto Kátia Carvalho | Impacto que transforma',
    'O Instituto | Instituto Katia Carvalho': 'O Instituto | Instituto Kátia Carvalho',
    'Projetos | Instituto Katia Carvalho': 'Projetos | Instituto Kátia Carvalho',
    'Transparência | Instituto Katia Carvalho': 'Transparência | Instituto Kátia Carvalho',
    'Voluntariado | Instituto Katia Carvalho': 'Voluntariado | Instituto Kátia Carvalho',
    'Contato | Instituto Katia Carvalho': 'Contato | Instituto Kátia Carvalho',
    'Instituto Katia Carvalho: solidariedade, inclusão e desenvolvimento social.': 'Instituto Kátia Carvalho: solidariedade, inclusão e desenvolvimento social.',
    'Conheça o Instituto Katia Carvalho, sua missão e áreas de atuação.': 'Conheça o Instituto Kátia Carvalho, sua missão e áreas de atuação.',
    'Projetos do Instituto Katia Carvalho.': 'Projetos do Instituto Kátia Carvalho.',
    'Transparência e documentos do Instituto Katia Carvalho.': 'Transparência e documentos do Instituto Katia Carvalho.',
    'Seja voluntário do Instituto Katia Carvalho.': 'Seja voluntário do Instituto Katia Carvalho.',
    'Entre em contato com o Instituto Katia Carvalho.': 'Entre em contato com o Instituto Katia Carvalho.',
    'Solidariedade que aproxima': 'Solidariedade que aproxima',
    'Transformando vidas através da solidariedade, inclusão e desenvolvimento social.': 'Transformando vidas através da solidariedade, inclusão e desenvolvimento social.',
    'Construímos oportunidades e fortalecemos comunidades para que cada pessoa possa participar de um futuro mais justo.': 'Construímos oportunidades e fortalecemos comunidades para que cada pessoa possa participar de um futuro mais justo.',
    'Conheça nosso trabalho': 'Conheça nosso trabalho', 'áreas para promover cidadania, autonomia e bem-estar.': 'áreas para promover cidadania, autonomia e bem-estar.',
    'Quem somos': 'Quem somos', 'Quem Somos': 'Quem somos', 'Presença que gera possibilidades.': 'Presença que gera possibilidades.',
    'O Instituto Kátia Carvalho é uma associação sem fins lucrativos, dedicada à promoção da cidadania, inclusão social e desenvolvimento comunitário. Atuamos sem discriminação de raça, gênero ou religião, sempre com foco no impacto social.': 'O Instituto Kátia Carvalho é uma associação sem fins lucrativos, dedicada à promoção da cidadania, inclusão social e desenvolvimento comunitário. Atuamos sem discriminação de raça, gênero ou religião, sempre com foco no impacto social.',
    'O Instituto Katia Carvalho é uma associação sem fins lucrativos, dedicada à promoção da cidadania, inclusão social e desenvolvimento comunitário. Atuamos sem discriminação de raça, gênero ou religião, sempre com foco no impacto social.': 'O Instituto Kátia Carvalho é uma associação sem fins lucrativos, dedicada à promoção da cidadania, inclusão social e desenvolvimento comunitário. Atuamos sem discriminação de raça, gênero ou religião, sempre com foco no impacto social.',
    'Trabalhamos lado a lado com comunidades, parceiros e voluntários para construir soluções que respeitam os territórios e fortalecem a autonomia das pessoas.': 'Trabalhamos lado a lado com comunidades, parceiros e voluntários para construir soluções que respeitam os territórios e fortalecem a autonomia das pessoas.',
    'Nossa missão': 'Nossa missão', 'Atuação que começa nas necessidades reais.': 'Atuação que começa nas necessidades reais.',
    'Unimos pessoas, conhecimento e recursos para cuidar do presente e abrir caminhos para o futuro.': 'Unimos pessoas, conhecimento e recursos para cuidar do presente e abrir caminhos para o futuro.',
    'Áreas de atuação': 'Áreas de atuação', 'Agricultura familiar': 'Agricultura familiar', 'Cidadania': 'Cidadania',
    'Segurança alimentar': 'Segurança alimentar', 'Apoio às mães': 'Apoio às mães', 'Assistência social': 'Assistência social',
    'Inclusão e acessibilidade': 'Inclusão e acessibilidade', 'Esporte e qualidade de vida': 'Esporte e qualidade de vida',
    'Saúde': 'Saúde', 'Moradia e bem-estar': 'Moradia e bem-estar', 'Tecnologia e inovação': 'Tecnologia e inovação',
    'Tecnologia e Inovação': 'Tecnologia e inovação', 'Ideias que viram ação no território.': 'Ideias que viram ação no território.',
    'Conheça algumas das frentes que aproximam cuidado, oportunidade e transformação.': 'Conheça algumas das frentes que aproximam cuidado, oportunidade e transformação.',
    'Conheça frentes que podem crescer com o apoio de pessoas e organizações parceiras.': 'Conheça frentes que podem crescer com o apoio de pessoas e organizações parceiras.',
    'Nossas iniciativas': 'Nossas iniciativas', 'Projetos em movimento': 'Projetos em movimento',
    'Rede de cuidado': 'Rede de cuidado', 'Apoio e formação para mães e famílias em situação de vulnerabilidade.': 'Apoio e formação para mães e famílias em situação de vulnerabilidade.',
    'Apoio e formação para mães e famílias em situação de vulnerabilidade, com rodas de conversa, orientação e encaminhamento para serviços.': 'Apoio e formação para mães e famílias em situação de vulnerabilidade, com rodas de conversa, orientação e encaminhamento para serviços.',
    'Juntos pelo futuro': 'Juntos pelo futuro', 'Atividades que conectam educação, esporte e desenvolvimento integral.': 'Atividades que conectam educação, esporte e desenvolvimento integral.',
    'Educação, esporte e desenvolvimento integral para crianças e adolescentes.': 'Educação, esporte e desenvolvimento integral para crianças e adolescentes.',
    'Atividades que conectam educação, esporte e desenvolvimento integral para crianças e adolescentes.': 'Atividades que conectam educação, esporte e desenvolvimento integral para crianças e adolescentes.',
    'Comunidade ativa': 'Comunidade ativa', 'Mobilização local para ampliar acesso a direitos e oportunidades.': 'Mobilização local para ampliar acesso a direitos e oportunidades.',
    'Mobilização local para ampliar o acesso a direitos, oportunidades e redes de proteção.': 'Mobilização local para ampliar o acesso a direitos, oportunidades e redes de proteção.',
    'Saiba mais': 'Saiba mais', 'Saiba mais →': 'Saiba mais →', 'Quero conhecer': 'Quero conhecer',
    'Mulheres reunidas em uma atividade comunitária': 'Mulheres reunidas em uma atividade comunitária',
    'Mulheres reunidas em atividade comunitária': 'Mulheres reunidas em atividade comunitária',
    'Crianças aprendendo juntas': 'Crianças aprendendo juntas', 'Mãos formando um círculo de união': 'Mãos formando um círculo de união',
    'Mãos formando um círculo': 'Mãos formando um círculo', 'Atividade comunitária': 'Atividade comunitária',
    'Transparência': 'Transparência', 'Confiança se constrói com clareza.': 'Confiança se constrói com clareza.',
    'Acompanhe documentos, resultados e informações sobre a nossa atuação.': 'Acompanhe documentos, resultados e informações sobre a nossa atuação.',
    'Acompanhe documentos, resultados e informações sobre a atuação do Instituto.': 'Acompanhe documentos, resultados e informações sobre a atuação do Instituto.',
    'Acompanhe os documentos e informações que apresentam nossa atuação.': 'Acompanhe os documentos e informações que apresentam nossa atuação.',
    'Estatuto Social': 'Estatuto Social', 'Ata de Assembleia': 'Ata de Assembleia', 'Relatórios anuais': 'Relatórios anuais',
    'Prestação de contas': 'Prestação de contas', 'Demonstrações financeiras': 'Demonstrações financeiras', 'Parcerias e convênios': 'Parcerias e convênios',
    'Tecnologia a serviço do impacto social': 'Tecnologia a serviço do impacto social',
    'Usamos ferramentas digitais para ampliar o alcance das iniciativas, apoiar decisões e tornar o cuidado mais eficiente e acessível.': 'Usamos ferramentas digitais para ampliar o alcance das iniciativas, apoiar decisões e tornar o cuidado mais eficiente e acessível.',
    'Projeto OMEGA': 'Projeto OMEGA', 'Sistemas digitais': 'Sistemas digitais', 'Automação e IA': 'Automação e IA',
    'Inteligência de dados e BI': 'Inteligência de dados e BI', 'Segurança da informação (LGPD)': 'Segurança da informação (LGPD)',
    'Inclusão digital': 'Inclusão digital', 'Seja voluntário': 'Seja voluntário', 'Seja Voluntário': 'Seja voluntário',
    'Junte-se a nós e faça parte da transformação social.': 'Junte-se a nós e faça parte da transformação social.',
    'Quero ser voluntário': 'Quero ser voluntário', 'Apoie esta causa': 'Apoie esta causa',
    'Seu apoio ajuda uma comunidade a seguir em frente.': 'Seu apoio ajuda uma comunidade a seguir em frente.',
    'Entre em contato para conhecer as formas de parceria, doação e participação no Instituto.': 'Entre em contato para conhecer as formas de parceria, doação e participação no Instituto.',
    'Vamos conversar?': 'Vamos conversar?', 'E-mail': 'E-mail', 'Faça parte desta rede': 'Faça parte desta rede',
    'Parcerias, voluntariado e apoio financeiro fortalecem o impacto de cada projeto.': 'Parcerias, voluntariado e apoio financeiro fortalecem o impacto de cada projeto.',
    'Entrar em contato': 'Entrar em contato', 'Solidariedade, inclusão e desenvolvimento comunitário.': 'Solidariedade, inclusão e desenvolvimento comunitário.',
    'Links rápidos': 'Links rápidos', 'Redes sociais': 'Redes sociais', '© Instituto Katia Carvalho – Todos os direitos reservados': '© Instituto Kátia Carvalho – Todos os direitos reservados',
    '© Instituto Katia Carvalho - Todos os direitos reservados': '© Instituto Kátia Carvalho - Todos os direitos reservados',
    'Política de privacidade': 'Política de privacidade', 'Instituto Katia Carvalho - Fomento ao Agro e Sustentabilidade': 'Instituto Kátia Carvalho - Fomento ao Agro e Sustentabilidade',
    'Logo do Instituto Katia Carvalho': 'Logo do Instituto Kátia Carvalho', 'Ir para o conteúdo principal': 'Ir para o conteúdo principal',
    'Abrir menu': 'Abrir menu', 'Fechar menu': 'Fechar menu', 'Navegação principal': 'Navegação principal',
    'Uma rede dedicada a transformar realidades.': 'Uma rede dedicada a transformar realidades.',
    'Conheça a história, os princípios e as frentes que orientam o Instituto Katia Carvalho.': 'Conheça a história, os princípios e as frentes que orientam o Instituto Kátia Carvalho.',
    'Nossos princípios': 'Nossos princípios', 'Respeito e acolhimento': 'Respeito e acolhimento', 'Ética e transparência': 'Ética e transparência',
    'Inclusão e equidade': 'Inclusão e equidade', 'Participação comunitária': 'Participação comunitária', 'Responsabilidade social': 'Responsabilidade social',
    'Direcionadores': 'Direcionadores', 'Missão, visão e compromisso': 'Missão, visão e compromisso', 'Missão': 'Missão', 'Visão': 'Visão', 'Valor': 'Valor',
    'Promover cidadania, inclusão e desenvolvimento comunitário com ações que geram autonomia.': 'Promover cidadania, inclusão e desenvolvimento comunitário com ações que geram autonomia.',
    'Ser uma referência em impacto social, colaboração e cuidado com as pessoas.': 'Ser uma referência em impacto social, colaboração e cuidado com as pessoas.',
    'Agir com transparência, escuta e compromisso com resultados que importam.': 'Agir com transparência, escuta e compromisso com resultados que importam.',
    'Início / O Instituto': 'Início / O Instituto', 'Início / Projetos': 'Início / Projetos', 'Início / Transparência': 'Início / Transparência',
    'Início / Voluntariado': 'Início / Voluntariado', 'Início / Contato': 'Início / Contato',
    'Prestação de contas': 'Prestação de contas', 'Informação pública, compromisso permanente.': 'Informação pública, compromisso permanente.',
    'A transparência orienta nossas relações com a comunidade, apoiadores e parceiros. Reunimos nesta página os principais documentos institucionais e financeiros.': 'A transparência orienta nossas relações com a comunidade, apoiadores e parceiros. Reunimos nesta página os principais documentos institucionais e financeiros.',
    'Os arquivos serão disponibilizados e atualizados conforme os ciclos de prestação de contas do Instituto.': 'Os arquivos serão disponibilizados e atualizados conforme os ciclos de prestação de contas do Instituto.',
    'Responsabilidade': 'Responsabilidade', 'Nosso compromisso é comunicar decisões, resultados e recursos utilizados de forma clara e acessível.': 'Nosso compromisso é comunicar decisões, resultados e recursos utilizados de forma clara e acessível.',
    'Documentos': 'Documentos', 'Consulte nossos registros': 'Consulte nossos registros', 'Solicitar documento': 'Solicitar documento',
    'Juntem-se a nós e façam parte da transformação social.': 'Juntem-se a nós e façam parte da transformação social.',
    'Seu tempo, sua experiência e sua vontade de colaborar podem ampliar o alcance das nossas ações.': 'Seu tempo, sua experiência e sua vontade de colaborar podem ampliar o alcance das nossas ações.',
    'Como participar': 'Como participar', 'Todo talento pode fazer diferença.': 'Todo talento pode fazer diferença.',
    'O voluntariado aproxima pessoas que querem contribuir de forma prática com projetos de cidadania, apoio social, educação, tecnologia e mobilização comunitária.': 'O voluntariado aproxima pessoas que querem contribuir de forma prática com projetos de cidadania, apoio social, educação, tecnologia e mobilização comunitária.',
    'Atuação em projetos e eventos': 'Atuação em projetos e eventos', 'Mentoria e oficinas': 'Mentoria e oficinas',
    'Comunicação e mobilização': 'Comunicação e mobilização', 'Apoio administrativo e tecnológico': 'Apoio administrativo e tecnológico',
    'Vamos encontrar seu lugar': 'Vamos encontrar seu lugar',
    'Conte um pouco sobre você, seus interesses e sua disponibilidade. Nossa equipe entrará em contato para conversar.': 'Conte um pouco sobre você, seus interesses e sua disponibilidade. Nossa equipe entrará em contato para conversar.',
    'Uma rede maior': 'Uma rede maior', 'Quando colaboramos, o impacto vai mais longe.': 'Quando colaboramos, o impacto vai mais longe.',
    'Faça parte de uma comunidade que acredita no cuidado e na construção coletiva.': 'Faça parte de uma comunidade que acredita no cuidado e na construção coletiva.',
    'Parcerias, voluntariado e apoio financeiro começam com uma boa conversa.': 'Parcerias, voluntariado e apoio financeiro começam com uma boa conversa.',
    'Fale com o Instituto': 'Fale com o Instituto', 'Estamos à disposição.': 'Estamos à disposição.',
    'Nome': 'Nome', 'Assunto': 'Assunto', 'Mensagem': 'Mensagem', 'Enviar mensagem': 'Enviar mensagem',
    'Quero propor uma parceria': 'Quero propor uma parceria', 'Outro assunto': 'Outro assunto',
    'Este formulário abre o aplicativo de e-mail padrão do dispositivo.': 'Este formulário abre o aplicativo de e-mail padrão do dispositivo.',
    'Cuidado e autonomia': 'Cuidado e autonomia', 'Educação e esporte': 'Educação e esporte', 'Mobilização local': 'Mobilização local',
    'Diretoria Executiva': 'Diretoria Executiva', 'CNPJ:': 'CNPJ:', 'Presidente da Diretoria': 'Presidente da Diretoria',
    'Vice-presidente': 'Vice-presidente', 'Secretário': 'Secretário', 'Tesoureiro': 'Tesoureiro', 'Formação: Teóloga': 'Formação: Teóloga',
    'Cargo: Presidente da Diretoria': 'Cargo: Presidente da Diretoria', 'Cargo: Vice-presidente': 'Cargo: Vice-presidente',
    'Cargo: Secretário': 'Cargo: Secretário', 'Profissão: Corretor de imóveis': 'Profissão: Corretor de imóveis',
    'Cargo: Tesoureiro': 'Cargo: Tesoureiro', 'Profissão: Trader e gestor financeiro': 'Profissão: Trader e gestor financeiro',
    'Membros do Conselho Fiscal': 'Membros do Conselho Fiscal', '1º Membro': '1º Membro', '2º Membro': '2º Membro',
    'Cargo: 1º Membro do Conselho Fiscal': 'Cargo: 1º Membro do Conselho Fiscal', 'Profissão: Autônomo': 'Profissão: Autônomo',
    'Cargo: 2º Membro do Conselho Fiscal': 'Cargo: 2º Membro do Conselho Fiscal', 'Profissão: Empresário': 'Profissão: Empresário',
    'Katia Simone Ribeiro Carvalho': 'Katia Simone Ribeiro Carvalho', 'Eliete Rodrigues Chaves': 'Eliete Rodrigues Chaves',
    'João Vitor Chaves Romão de Souza': 'João Vitor Chaves Romão de Souza', 'Jorge Alberto Scotta': 'Jorge Alberto Scotta',
    'Ronaldo Zickenrodt': 'Ronaldo Zickenrodt', 'Sidney Santos Souza': 'Sidney Santos Souza'
  },
  en: {},
  es: {}
};

translations.en = {
  ...translations.pt,
  'Início': 'Home', 'O Instituto': 'About Us', 'Projetos': 'Projects', 'Transparência': 'Transparency', 'Voluntariado': 'Volunteer', 'Contato': 'Contact', 'Quero apoiar': 'Support us',
  'Instituto Kátia Carvalho': 'Instituto Kátia Carvalho', 'Instituto Katia Carvalho': 'Instituto Kátia Carvalho', 'Impacto social': 'Social impact',
  'Instituto Katia Carvalho | Impacto que transforma': 'Instituto Kátia Carvalho | Impact that transforms', 'O Instituto | Instituto Katia Carvalho': 'About Us | Instituto Kátia Carvalho',
  'Projetos | Instituto Katia Carvalho': 'Projects | Instituto Kátia Carvalho', 'Transparência | Instituto Katia Carvalho': 'Transparency | Instituto Kátia Carvalho',
  'Voluntariado | Instituto Katia Carvalho': 'Volunteer | Instituto Kátia Carvalho', 'Contato | Instituto Katia Carvalho': 'Contact | Instituto Kátia Carvalho',
  'Instituto Katia Carvalho: solidariedade, inclusão e desenvolvimento social.': 'Instituto Kátia Carvalho: solidarity, inclusion, and social development.',
  'Conheça o Instituto Katia Carvalho, sua missão e áreas de atuação.': 'Learn about Instituto Kátia Carvalho, its mission, and areas of work.',
  'Projetos do Instituto Katia Carvalho.': 'Projects by Instituto Kátia Carvalho.', 'Transparência e documentos do Instituto Katia Carvalho.': 'Transparency and documents from Instituto Kátia Carvalho.',
  'Seja voluntário do Instituto Katia Carvalho.': 'Volunteer with Instituto Kátia Carvalho.', 'Entre em contato com o Instituto Katia Carvalho.': 'Contact Instituto Kátia Carvalho.',
  'Solidariedade que aproxima': 'Solidarity that brings us together', 'Transformando vidas através da solidariedade, inclusão e desenvolvimento social.': 'Transforming lives through solidarity, inclusion, and social development.',
  'Construímos oportunidades e fortalecemos comunidades para que cada pessoa possa participar de um futuro mais justo.': 'We build opportunities and strengthen communities so everyone can take part in a fairer future.',
  'Conheça nosso trabalho': 'Discover our work', 'áreas para promover cidadania, autonomia e bem-estar.': 'areas promoting citizenship, autonomy, and well-being.',
  'Quem somos': 'Who we are', 'Quem Somos': 'Who we are', 'Presença que gera possibilidades.': 'A presence that creates possibilities.',
  'O Instituto Kátia Carvalho é uma associação sem fins lucrativos, dedicada à promoção da cidadania, inclusão social e desenvolvimento comunitário. Atuamos sem discriminação de raça, gênero ou religião, sempre com foco no impacto social.': 'Instituto Kátia Carvalho is a nonprofit organization dedicated to promoting citizenship, social inclusion, and community development. We work without discrimination based on race, gender, or religion, always focused on social impact.',
  'O Instituto Katia Carvalho é uma associação sem fins lucrativos, dedicada à promoção da cidadania, inclusão social e desenvolvimento comunitário. Atuamos sem discriminação de raça, gênero ou religião, sempre com foco no impacto social.': 'Instituto Kátia Carvalho is a nonprofit organization dedicated to promoting citizenship, social inclusion, and community development. We work without discrimination based on race, gender, or religion, always focused on social impact.',
  'Trabalhamos lado a lado com comunidades, parceiros e voluntários para construir soluções que respeitam os territórios e fortalecem a autonomia das pessoas.': 'We work alongside communities, partners, and volunteers to build solutions that respect local contexts and strengthen people’s autonomy.',
  'Nossa missão': 'Our mission', 'Atuação que começa nas necessidades reais.': 'Work that starts with real needs.', 'Unimos pessoas, conhecimento e recursos para cuidar do presente e abrir caminhos para o futuro.': 'We bring people, knowledge, and resources together to care for today and open paths for tomorrow.',
  'Áreas de atuação': 'Areas of work', 'Agricultura familiar': 'Family farming', 'Cidadania': 'Citizenship', 'Segurança alimentar': 'Food security', 'Apoio às mães': 'Support for mothers', 'Assistência social': 'Social assistance', 'Inclusão e acessibilidade': 'Inclusion and accessibility', 'Esporte e qualidade de vida': 'Sports and well-being', 'Saúde': 'Health', 'Moradia e bem-estar': 'Housing and well-being', 'Tecnologia e inovação': 'Technology and innovation', 'Tecnologia e Inovação': 'Technology and innovation',
  'Ideias que viram ação no território.': 'Ideas put into action in our communities.', 'Conheça algumas das frentes que aproximam cuidado, oportunidade e transformação.': 'Explore initiatives that bring care, opportunity, and transformation together.', 'Conheça frentes que podem crescer com o apoio de pessoas e organizações parceiras.': 'Explore initiatives that can grow with support from individuals and partner organizations.', 'Nossas iniciativas': 'Our initiatives', 'Projetos em movimento': 'Projects in action',
  'Rede de cuidado': 'Care network', 'Apoio e formação para mães e famílias em situação de vulnerabilidade.': 'Support and training for mothers and families facing vulnerability.', 'Apoio e formação para mães e famílias em situação de vulnerabilidade, com rodas de conversa, orientação e encaminhamento para serviços.': 'Support and training for mothers and families facing vulnerability, including discussion groups, guidance, and referrals to services.',
  'Juntos pelo futuro': 'Together for the future', 'Atividades que conectam educação, esporte e desenvolvimento integral.': 'Activities connecting education, sports, and holistic development.', 'Educação, esporte e desenvolvimento integral para crianças e adolescentes.': 'Education, sports, and holistic development for children and teens.', 'Atividades que conectam educação, esporte e desenvolvimento integral para crianças e adolescentes.': 'Activities connecting education, sports, and holistic development for children and teens.',
  'Comunidade ativa': 'Active community', 'Mobilização local para ampliar acesso a direitos e oportunidades.': 'Local action to expand access to rights and opportunities.', 'Mobilização local para ampliar o acesso a direitos, oportunidades e redes de proteção.': 'Local action to expand access to rights, opportunities, and support networks.', 'Saiba mais': 'Learn more', 'Saiba mais →': 'Learn more →', 'Quero conhecer': 'I want to learn more',
  'Mulheres reunidas em uma atividade comunitária': 'Women gathered for a community activity', 'Mulheres reunidas em atividade comunitária': 'Women gathered for a community activity', 'Crianças aprendendo juntas': 'Children learning together', 'Mãos formando um círculo de união': 'Hands forming a circle of unity', 'Mãos formando um círculo': 'Hands forming a circle', 'Atividade comunitária': 'Community activity',
  'Confiança se constrói com clareza.': 'Trust is built through transparency.', 'Acompanhe documentos, resultados e informações sobre a nossa atuação.': 'Explore documents, results, and information about our work.', 'Acompanhe documentos, resultados e informações sobre a atuação do Instituto.': 'Explore documents, results, and information about the Institute’s work.', 'Acompanhe os documentos e informações que apresentam nossa atuação.': 'Explore documents and information about our work.',
  'Estatuto Social': 'Bylaws', 'Ata de Assembleia': 'Meeting minutes', 'Relatórios anuais': 'Annual reports', 'Prestação de contas': 'Financial accountability', 'Demonstrações financeiras': 'Financial statements', 'Parcerias e convênios': 'Partnerships and agreements',
  'Tecnologia a serviço do impacto social': 'Technology in service of social impact', 'Usamos ferramentas digitais para ampliar o alcance das iniciativas, apoiar decisões e tornar o cuidado mais eficiente e acessível.': 'We use digital tools to extend the reach of our initiatives, support decision-making, and make care more effective and accessible.', 'Projeto OMEGA': 'OMEGA Project', 'Sistemas digitais': 'Digital systems', 'Automação e IA': 'Automation and AI', 'Inteligência de dados e BI': 'Data intelligence and BI', 'Segurança da informação (LGPD)': 'Information security (Brazilian data protection law)', 'Inclusão digital': 'Digital inclusion',
  'Seja voluntário': 'Volunteer', 'Seja Voluntário': 'Volunteer', 'Junte-se a nós e faça parte da transformação social.': 'Join us and be part of social change.', 'Quero ser voluntário': 'I want to volunteer', 'Apoie esta causa': 'Support this cause', 'Seu apoio ajuda uma comunidade a seguir em frente.': 'Your support helps a community move forward.', 'Entre em contato para conhecer as formas de parceria, doação e participação no Instituto.': 'Contact us to learn how to partner, donate, or get involved with the Institute.', 'Vamos conversar?': 'Let’s talk', 'E-mail': 'Email', 'Faça parte desta rede': 'Join this network', 'Parcerias, voluntariado e apoio financeiro fortalecem o impacto de cada projeto.': 'Partnerships, volunteering, and financial support strengthen every project’s impact.', 'Entrar em contato': 'Get in touch', 'Solidariedade, inclusão e desenvolvimento comunitário.': 'Solidarity, inclusion, and community development.', 'Links rápidos': 'Quick links', 'Redes sociais': 'Social media',
  '© Instituto Katia Carvalho – Todos os direitos reservados': '© Instituto Kátia Carvalho. All rights reserved.', '© Instituto Katia Carvalho - Todos os direitos reservados': '© Instituto Kátia Carvalho. All rights reserved.', 'Política de privacidade': 'Privacy policy', 'Instituto Katia Carvalho - Fomento ao Agro e Sustentabilidade': 'Instituto Kátia Carvalho - Promoting Agriculture and Sustainability', 'Logo do Instituto Katia Carvalho': 'Instituto Kátia Carvalho logo', 'Ir para o conteúdo principal': 'Skip to main content', 'Abrir menu': 'Open menu', 'Fechar menu': 'Close menu', 'Navegação principal': 'Main navigation',
  'Uma rede dedicada a transformar realidades.': 'A network dedicated to transforming lives.', 'Conheça a história, os princípios e as frentes que orientam o Instituto Katia Carvalho.': 'Learn about the history, principles, and initiatives that guide Instituto Kátia Carvalho.', 'Nossos princípios': 'Our principles', 'Respeito e acolhimento': 'Respect and welcome', 'Ética e transparência': 'Ethics and transparency', 'Inclusão e equidade': 'Inclusion and equity', 'Participação comunitária': 'Community participation', 'Responsabilidade social': 'Social responsibility', 'Direcionadores': 'Guiding principles', 'Missão, visão e compromisso': 'Mission, vision, and commitment', 'Missão': 'Mission', 'Visão': 'Vision', 'Valor': 'Value', 'Promover cidadania, inclusão e desenvolvimento comunitário com ações que geram autonomia.': 'Promote citizenship, inclusion, and community development through actions that foster autonomy.', 'Ser uma referência em impacto social, colaboração e cuidado com as pessoas.': 'Become a reference in social impact, collaboration, and care for people.', 'Agir com transparência, escuta e compromisso com resultados que importam.': 'Act with transparency, attentive listening, and commitment to meaningful results.',
  'Início / O Instituto': 'Home / About Us', 'Início / Projetos': 'Home / Projects', 'Início / Transparência': 'Home / Transparency', 'Início / Voluntariado': 'Home / Volunteer', 'Início / Contato': 'Home / Contact',
  'Informação pública, compromisso permanente.': 'Public information, an ongoing commitment.', 'A transparência orienta nossas relações com a comunidade, apoiadores e parceiros. Reunimos nesta página os principais documentos institucionais e financeiros.': 'Transparency guides our relationships with the community, supporters, and partners. This page brings together our key institutional and financial documents.', 'Os arquivos serão disponibilizados e atualizados conforme os ciclos de prestação de contas do Instituto.': 'Files will be made available and updated according to the Institute’s reporting cycles.', 'Responsabilidade': 'Accountability', 'Nosso compromisso é comunicar decisões, resultados e recursos utilizados de forma clara e acessível.': 'We are committed to communicating decisions, results, and the use of resources clearly and accessibly.', 'Documentos': 'Documents', 'Consulte nossos registros': 'View our records', 'Solicitar documento': 'Request document',
  'Seu tempo, sua experiência e sua vontade de colaborar podem ampliar o alcance das nossas ações.': 'Your time, experience, and willingness to help can extend the reach of our work.', 'Como participar': 'How to get involved', 'Todo talento pode fazer diferença.': 'Every talent can make a difference.', 'O voluntariado aproxima pessoas que querem contribuir de forma prática com projetos de cidadania, apoio social, educação, tecnologia e mobilização comunitária.': 'Volunteering connects people who want to make a practical contribution to citizenship, social support, education, technology, and community engagement projects.', 'Atuação em projetos e eventos': 'Projects and events', 'Mentoria e oficinas': 'Mentoring and workshops', 'Comunicação e mobilização': 'Communications and outreach', 'Apoio administrativo e tecnológico': 'Administrative and technology support', 'Vamos encontrar seu lugar': 'Let’s find the right fit', 'Conte um pouco sobre você, seus interesses e sua disponibilidade. Nossa equipe entrará em contato para conversar.': 'Tell us a little about yourself, your interests, and your availability. Our team will get in touch.', 'Uma rede maior': 'A wider network', 'Quando colaboramos, o impacto vai mais longe.': 'When we work together, our impact goes further.', 'Faça parte de uma comunidade que acredita no cuidado e na construção coletiva.': 'Join a community that believes in care and building together.', 'Parcerias, voluntariado e apoio financeiro começam com uma boa conversa.': 'Partnerships, volunteering, and financial support start with a good conversation.', 'Fale com o Instituto': 'Contact the Institute', 'Estamos à disposição.': 'We are here to help.', 'Nome': 'Name', 'Assunto': 'Subject', 'Mensagem': 'Message', 'Enviar mensagem': 'Send message', 'Quero propor uma parceria': 'I would like to propose a partnership', 'Outro assunto': 'Other', 'Este formulário abre o aplicativo de e-mail padrão do dispositivo.': 'This form opens your device’s default email app.', 'Cuidado e autonomia': 'Care and autonomy', 'Educação e esporte': 'Education and sports', 'Mobilização local': 'Community action',
  'Diretoria Executiva': 'Executive Board', 'CNPJ:': 'CNPJ (Brazilian company registration):', 'Presidente da Diretoria': 'President of the Board', 'Vice-presidente': 'Vice President', 'Secretário': 'Secretary', 'Tesoureiro': 'Treasurer', 'Formação: Teóloga': 'Education: Theologian', 'Cargo: Presidente da Diretoria': 'Role: Board President', 'Cargo: Vice-presidente': 'Role: Vice President', 'Cargo: Secretário': 'Role: Secretary', 'Profissão: Corretor de imóveis': 'Profession: Real estate agent', 'Cargo: Tesoureiro': 'Role: Treasurer', 'Profissão: Trader e gestor financeiro': 'Profession: Trader and financial manager', 'Membros do Conselho Fiscal': 'Fiscal Council Members', '1º Membro': '1st Member', '2º Membro': '2nd Member', 'Cargo: 1º Membro do Conselho Fiscal': 'Role: 1st Fiscal Council Member', 'Profissão: Autônomo': 'Profession: Self-employed', 'Cargo: 2º Membro do Conselho Fiscal': 'Role: 2nd Fiscal Council Member', 'Profissão: Empresário': 'Profession: Business owner',
  'Katia Simone Ribeiro Carvalho': 'Katia Simone Ribeiro Carvalho', 'Eliete Rodrigues Chaves': 'Eliete Rodrigues Chaves', 'João Vitor Chaves Romão de Souza': 'João Vitor Chaves Romão de Souza', 'Jorge Alberto Scotta': 'Jorge Alberto Scotta', 'Ronaldo Zickenrodt': 'Ronaldo Zickenrodt', 'Sidney Santos Souza': 'Sidney Santos Souza'
};
translations.pt['Governança'] = 'Governança';
translations.pt['Instituto Katia Carvalho, início'] = 'Instituto Kátia Carvalho, início';
translations.pt['Projeto de tecnologia e inovação do Instituto Katia Carvalho.'] = 'Projeto de tecnologia e inovação do Instituto Kátia Carvalho.';
translations.en['Governança'] = 'Governance';
translations.en['Instituto Katia Carvalho, início'] = 'Instituto Kátia Carvalho, home';
translations.en['Projeto de tecnologia e inovação do Instituto Katia Carvalho.'] = 'Instituto Kátia Carvalho technology and innovation project.';

translations.es = {
  ...translations.pt,
  'Início': 'Inicio', 'O Instituto': 'El Instituto', 'Projetos': 'Proyectos', 'Transparência': 'Transparencia', 'Voluntariado': 'Voluntariado', 'Contato': 'Contacto', 'Quero apoiar': 'Quiero apoyar',
  'Instituto Kátia Carvalho': 'Instituto Kátia Carvalho', 'Instituto Katia Carvalho': 'Instituto Kátia Carvalho', 'Impacto social': 'Impacto social',
  'Instituto Katia Carvalho | Impacto que transforma': 'Instituto Kátia Carvalho | Impacto que transforma', 'O Instituto | Instituto Katia Carvalho': 'El Instituto | Instituto Kátia Carvalho', 'Projetos | Instituto Katia Carvalho': 'Proyectos | Instituto Kátia Carvalho', 'Transparência | Instituto Katia Carvalho': 'Transparencia | Instituto Kátia Carvalho', 'Voluntariado | Instituto Katia Carvalho': 'Voluntariado | Instituto Kátia Carvalho', 'Contato | Instituto Katia Carvalho': 'Contacto | Instituto Kátia Carvalho',
  'Instituto Katia Carvalho: solidariedade, inclusão e desenvolvimento social.': 'Instituto Kátia Carvalho: solidaridad, inclusión y desarrollo social.', 'Conheça o Instituto Katia Carvalho, sua missão e áreas de atuação.': 'Conozca el Instituto Kátia Carvalho, su misión y sus áreas de actuación.', 'Projetos do Instituto Katia Carvalho.': 'Proyectos del Instituto Kátia Carvalho.', 'Transparência e documentos do Instituto Katia Carvalho.': 'Transparencia y documentos del Instituto Kátia Carvalho.', 'Seja voluntário do Instituto Katia Carvalho.': 'Sea voluntario del Instituto Kátia Carvalho.', 'Entre em contato com o Instituto Katia Carvalho.': 'Póngase en contacto con el Instituto Kátia Carvalho.',
  'Solidariedade que aproxima': 'La solidaridad nos une', 'Transformando vidas através da solidariedade, inclusão e desenvolvimento social.': 'Transformamos vidas mediante la solidaridad, la inclusión y el desarrollo social.', 'Construímos oportunidades e fortalecemos comunidades para que cada pessoa possa participar de um futuro mais justo.': 'Creamos oportunidades y fortalecemos comunidades para que todas las personas puedan participar de un futuro más justo.', 'Conheça nosso trabalho': 'Conozca nuestro trabajo', 'áreas para promover cidadania, autonomia e bem-estar.': 'áreas para promover la ciudadanía, la autonomía y el bienestar.',
  'Quem somos': 'Quiénes somos', 'Quem Somos': 'Quiénes somos', 'Presença que gera possibilidades.': 'Presencia que crea posibilidades.', 'O Instituto Kátia Carvalho é uma associação sem fins lucrativos, dedicada à promoção da cidadania, inclusão social e desenvolvimento comunitário. Atuamos sem discriminação de raça, gênero ou religião, sempre com foco no impacto social.': 'El Instituto Kátia Carvalho es una asociación sin fines de lucro dedicada a promover la ciudadanía, la inclusión social y el desarrollo comunitario. Trabajamos sin discriminación por raza, género o religión, siempre enfocados en el impacto social.', 'O Instituto Katia Carvalho é uma associação sem fins lucrativos, dedicada à promoção da cidadania, inclusão social e desenvolvimento comunitário. Atuamos sem discriminação de raça, gênero ou religião, sempre com foco no impacto social.': 'El Instituto Kátia Carvalho es una asociación sin fines de lucro dedicada a promover la ciudadanía, la inclusión social y el desarrollo comunitario. Trabajamos sin discriminación por raza, género o religión, siempre enfocados en el impacto social.',
  'Trabalhamos lado a lado com comunidades, parceiros e voluntários para construir soluções que respeitam os territórios e fortalecem a autonomia das pessoas.': 'Trabajamos junto con las comunidades, los socios y las personas voluntarias para crear soluciones que respetan los territorios y fortalecen la autonomía de las personas.', 'Nossa missão': 'Nuestra misión', 'Atuação que começa nas necessidades reais.': 'Acciones que comienzan con necesidades reales.', 'Unimos pessoas, conhecimento e recursos para cuidar do presente e abrir caminhos para o futuro.': 'Unimos personas, conocimientos y recursos para cuidar el presente y abrir caminos hacia el futuro.', 'Áreas de atuação': 'Áreas de actuación',
  'Agricultura familiar': 'Agricultura familiar', 'Cidadania': 'Ciudadanía', 'Segurança alimentar': 'Seguridad alimentaria', 'Apoio às mães': 'Apoyo a las madres', 'Assistência social': 'Asistencia social', 'Inclusão e acessibilidade': 'Inclusión y accesibilidad', 'Esporte e qualidade de vida': 'Deporte y calidad de vida', 'Saúde': 'Salud', 'Moradia e bem-estar': 'Vivienda y bienestar', 'Tecnologia e inovação': 'Tecnología e innovación', 'Tecnologia e Inovação': 'Tecnología e innovación', 'Ideias que viram ação no território.': 'Ideas que se convierten en acción en la comunidad.', 'Conheça algumas das frentes que aproximam cuidado, oportunidade e transformação.': 'Conozca algunas iniciativas que acercan el cuidado, las oportunidades y la transformación.', 'Conheça frentes que podem crescer com o apoio de pessoas e organizações parceiras.': 'Conozca iniciativas que pueden crecer con el apoyo de personas y organizaciones colaboradoras.', 'Nossas iniciativas': 'Nuestras iniciativas', 'Projetos em movimento': 'Proyectos en marcha',
  'Rede de cuidado': 'Red de cuidados', 'Apoio e formação para mães e famílias em situação de vulnerabilidade.': 'Apoyo y formación para madres y familias en situación de vulnerabilidad.', 'Apoio e formação para mães e famílias em situação de vulnerabilidade, com rodas de conversa, orientação e encaminhamento para serviços.': 'Apoyo y formación para madres y familias en situación de vulnerabilidad, con grupos de diálogo, orientación y derivación a servicios.', 'Juntos pelo futuro': 'Juntos por el futuro', 'Atividades que conectam educação, esporte e desenvolvimento integral.': 'Actividades que conectan la educación, el deporte y el desarrollo integral.', 'Educação, esporte e desenvolvimento integral para crianças e adolescentes.': 'Educación, deporte y desarrollo integral para niños, niñas y adolescentes.', 'Atividades que conectam educação, esporte e desenvolvimento integral para crianças e adolescentes.': 'Actividades que conectan la educación, el deporte y el desarrollo integral para niños, niñas y adolescentes.', 'Comunidade ativa': 'Comunidad activa', 'Mobilização local para ampliar acesso a direitos e oportunidades.': 'Movilización local para ampliar el acceso a derechos y oportunidades.', 'Mobilização local para ampliar o acesso a direitos, oportunidades e redes de proteção.': 'Movilización local para ampliar el acceso a derechos, oportunidades y redes de apoyo.', 'Saiba mais': 'Más información', 'Saiba mais →': 'Más información →', 'Quero conhecer': 'Quiero conocer',
  'Mulheres reunidas em uma atividade comunitária': 'Mujeres reunidas en una actividad comunitaria', 'Mulheres reunidas em atividade comunitária': 'Mujeres reunidas en una actividad comunitaria', 'Crianças aprendendo juntas': 'Niños y niñas aprendiendo juntos', 'Mãos formando um círculo de união': 'Manos formando un círculo de unión', 'Mãos formando um círculo': 'Manos formando un círculo', 'Atividade comunitária': 'Actividad comunitaria',
  'Confiança se constrói com clareza.': 'La confianza se construye con transparencia.', 'Acompanhe documentos, resultados e informações sobre a nossa atuação.': 'Consulte documentos, resultados e datos sobre nuestro trabajo.', 'Acompanhe documentos, resultados e informações sobre a atuação do Instituto.': 'Consulte documentos, resultados y datos sobre el trabajo del Instituto.', 'Acompanhe os documentos e informações que apresentam nossa atuação.': 'Consulte los documentos y la información sobre nuestro trabajo.', 'Estatuto Social': 'Estatuto social', 'Ata de Assembleia': 'Acta de asamblea', 'Relatórios anuais': 'Informes anuales', 'Prestação de contas': 'Rendición de cuentas', 'Demonstrações financeiras': 'Estados financieros', 'Parcerias e convênios': 'Alianzas y convenios',
  'Tecnologia a serviço do impacto social': 'Tecnología al servicio del impacto social', 'Usamos ferramentas digitais para ampliar o alcance das iniciativas, apoiar decisões e tornar o cuidado mais eficiente e acessível.': 'Utilizamos herramientas digitales para ampliar el alcance de las iniciativas, apoyar la toma de decisiones y hacer que la atención sea más eficaz y accesible.', 'Projeto OMEGA': 'Proyecto OMEGA', 'Sistemas digitais': 'Sistemas digitales', 'Automação e IA': 'Automatización e IA', 'Inteligência de dados e BI': 'Inteligencia de datos y BI', 'Segurança da informação (LGPD)': 'Seguridad de la información (ley brasileña de protección de datos)', 'Inclusão digital': 'Inclusión digital', 'Seja voluntário': 'Sea voluntario', 'Seja Voluntário': 'Sea voluntario', 'Junte-se a nós e faça parte da transformação social.': 'Únase a nosotros y sea parte de la transformación social.', 'Quero ser voluntário': 'Quiero ser voluntario', 'Apoie esta causa': 'Apoye esta causa', 'Seu apoio ajuda uma comunidade a seguir em frente.': 'Su apoyo ayuda a una comunidad a seguir adelante.', 'Entre em contato para conhecer as formas de parceria, doação e participação no Instituto.': 'Contáctenos para conocer las formas de colaboración, donación y participación en el Instituto.', 'Vamos conversar?': '¿Hablamos?', 'E-mail': 'Correo electrónico', 'Faça parte desta rede': 'Forme parte de esta red', 'Parcerias, voluntariado e apoio financeiro fortalecem o impacto de cada projeto.': 'Las alianzas, el voluntariado y el apoyo financiero fortalecen el impacto de cada proyecto.', 'Entrar em contato': 'Contactar', 'Solidariedade, inclusão e desenvolvimento comunitário.': 'Solidaridad, inclusión y desarrollo comunitario.', 'Links rápidos': 'Enlaces rápidos', 'Redes sociais': 'Redes sociales',
  '© Instituto Katia Carvalho – Todos os direitos reservados': '© Instituto Kátia Carvalho. Todos los derechos reservados.', '© Instituto Katia Carvalho - Todos os direitos reservados': '© Instituto Kátia Carvalho. Todos los derechos reservados.', 'Política de privacidade': 'Política de privacidad', 'Instituto Katia Carvalho - Fomento ao Agro e Sustentabilidade': 'Instituto Kátia Carvalho - Promoción de la agricultura y la sostenibilidad', 'Logo do Instituto Katia Carvalho': 'Logotipo del Instituto Kátia Carvalho', 'Ir para o conteúdo principal': 'Ir al contenido principal', 'Abrir menu': 'Abrir menú', 'Fechar menu': 'Cerrar menú', 'Navegação principal': 'Navegación principal',
  'Uma rede dedicada a transformar realidades.': 'Una red dedicada a transformar realidades.', 'Conheça a história, os princípios e as frentes que orientam o Instituto Katia Carvalho.': 'Conozca la historia, los principios y las iniciativas que guían al Instituto Kátia Carvalho.', 'Nossos princípios': 'Nuestros principios', 'Respeito e acolhimento': 'Respeto y acogida', 'Ética e transparência': 'Ética y transparencia', 'Inclusão e equidade': 'Inclusión y equidad', 'Participação comunitária': 'Participación comunitaria', 'Responsabilidade social': 'Responsabilidad social', 'Direcionadores': 'Principios orientadores', 'Missão, visão e compromisso': 'Misión, visión y compromiso', 'Missão': 'Misión', 'Visão': 'Visión', 'Valor': 'Valores', 'Promover cidadania, inclusão e desenvolvimento comunitário com ações que geram autonomia.': 'Promover la ciudadanía, la inclusión y el desarrollo comunitario mediante acciones que generan autonomía.', 'Ser uma referência em impacto social, colaboração e cuidado com as pessoas.': 'Ser un referente en impacto social, colaboración y atención a las personas.', 'Agir com transparência, escuta e compromisso com resultados que importam.': 'Actuar con transparencia, escucha y compromiso con resultados relevantes.',
  'Início / O Instituto': 'Inicio / El Instituto', 'Início / Projetos': 'Inicio / Proyectos', 'Início / Transparência': 'Inicio / Transparencia', 'Início / Voluntariado': 'Inicio / Voluntariado', 'Início / Contato': 'Inicio / Contacto', 'Informação pública, compromisso permanente.': 'Información pública, compromiso permanente.', 'A transparência orienta nossas relações com a comunidade, apoiadores e parceiros. Reunimos nesta página os principais documentos institucionais e financeiros.': 'La transparencia guía nuestras relaciones con la comunidad, las personas que apoyan y nuestros socios. Esta página reúne los principales documentos institucionales y financieros.', 'Os arquivos serão disponibilizados e atualizados conforme os ciclos de prestação de contas do Instituto.': 'Los archivos se publicarán y actualizarán según los ciclos de rendición de cuentas del Instituto.', 'Responsabilidade': 'Responsabilidad', 'Nosso compromisso é comunicar decisões, resultados e recursos utilizados de forma clara e acessível.': 'Nos comprometemos a comunicar decisiones, resultados y uso de recursos de manera clara y accesible.', 'Documentos': 'Documentos', 'Consulte nossos registros': 'Consulte nuestros registros', 'Solicitar documento': 'Solicitar documento',
  'Seu tempo, sua experiência e sua vontade de colaborar podem ampliar o alcance das nossas ações.': 'Su tiempo, experiencia y voluntad de colaborar pueden ampliar el alcance de nuestras acciones.', 'Como participar': 'Cómo participar', 'Todo talento pode fazer diferença.': 'Todos los talentos pueden marcar la diferencia.', 'O voluntariado aproxima pessoas que querem contribuir de forma prática com projetos de cidadania, apoio social, educação, tecnologia e mobilização comunitária.': 'El voluntariado conecta a personas que desean contribuir de forma práctica con proyectos de ciudadanía, apoyo social, educación, tecnología y movilización comunitaria.', 'Atuação em projetos e eventos': 'Participación en proyectos y eventos', 'Mentoria e oficinas': 'Mentoría y talleres', 'Comunicação e mobilização': 'Comunicación y movilización', 'Apoio administrativo e tecnológico': 'Apoyo administrativo y tecnológico', 'Vamos encontrar seu lugar': 'Encontraremos su lugar', 'Conte um pouco sobre você, seus interesses e sua disponibilidade. Nossa equipe entrará em contato para conversar.': 'Cuéntenos un poco sobre usted, sus intereses y su disponibilidad. Nuestro equipo se pondrá en contacto.', 'Uma rede maior': 'Una red más amplia', 'Quando colaboramos, o impacto vai mais longe.': 'Cuando colaboramos, el impacto llega más lejos.', 'Faça parte de uma comunidade que acredita no cuidado e na construção coletiva.': 'Forme parte de una comunidad que cree en el cuidado y la construcción colectiva.', 'Parcerias, voluntariado e apoio financeiro começam com uma boa conversa.': 'Las alianzas, el voluntariado y el apoyo financiero comienzan con una buena conversación.', 'Fale com o Instituto': 'Hable con el Instituto', 'Estamos à disposição.': 'Estamos a su disposición.', 'Nome': 'Nombre', 'Assunto': 'Asunto', 'Mensagem': 'Mensaje', 'Enviar mensagem': 'Enviar mensaje', 'Quero propor uma parceria': 'Quiero proponer una alianza', 'Outro assunto': 'Otro tema', 'Este formulário abre o aplicativo de e-mail padrão do dispositivo.': 'Este formulario abre la aplicación de correo electrónico predeterminada del dispositivo.', 'Cuidado e autonomia': 'Cuidado y autonomía', 'Educação e esporte': 'Educación y deporte', 'Mobilização local': 'Movilización local',
  'Diretoria Executiva': 'Directorio Ejecutivo', 'CNPJ:': 'CNPJ (registro brasileño de personas jurídicas):', 'Presidente da Diretoria': 'Presidente de la Junta Directiva', 'Vice-presidente': 'Vicepresidente', 'Secretário': 'Secretario', 'Tesoureiro': 'Tesorero', 'Formação: Teóloga': 'Formación: Teóloga', 'Cargo: Presidente da Diretoria': 'Cargo: Presidenta de la Junta Directiva', 'Cargo: Vice-presidente': 'Cargo: Vicepresidente', 'Cargo: Secretário': 'Cargo: Secretario', 'Profissão: Corretor de imóveis': 'Profesión: Agente inmobiliario', 'Cargo: Tesoureiro': 'Cargo: Tesorero', 'Profissão: Trader e gestor financeiro': 'Profesión: Operador financiero y gestor de inversiones', 'Membros do Conselho Fiscal': 'Miembros del Consejo Fiscal', '1º Membro': '1.er Miembro', '2º Membro': '2.º Miembro', 'Cargo: 1º Membro do Conselho Fiscal': 'Cargo: 1.er Miembro del Consejo Fiscal', 'Profissão: Autônomo': 'Profesión: Trabajador independiente', 'Cargo: 2º Membro do Conselho Fiscal': 'Cargo: 2.º Miembro del Consejo Fiscal', 'Profissão: Empresário': 'Profesión: Empresario',
  'Katia Simone Ribeiro Carvalho': 'Katia Simone Ribeiro Carvalho', 'Eliete Rodrigues Chaves': 'Eliete Rodrigues Chaves', 'João Vitor Chaves Romão de Souza': 'João Vitor Chaves Romão de Souza', 'Jorge Alberto Scotta': 'Jorge Alberto Scotta', 'Ronaldo Zickenrodt': 'Ronaldo Zickenrodt', 'Sidney Santos Souza': 'Sidney Santos Souza'
};
translations.es['Governança'] = 'Gobernanza';
translations.es['Instituto Katia Carvalho, início'] = 'Inicio del Instituto Kátia Carvalho';
translations.es['Projeto de tecnologia e inovação do Instituto Katia Carvalho.'] = 'Proyecto de tecnología e innovación del Instituto Kátia Carvalho.';

Object.assign(translations.en, {
        '/ Juntos pelo futuro': '/ Together for the Future',
      'OMEGA TECH COMUNIDADE: inclusão digital, tecnologia e desenvolvimento comunitário.': 'OMEGA TECH COMUNIDADE: digital inclusion, technology, and community development.',
      'Juntos pelo futuro: atividades de educação, esporte e desenvolvimento integral.': 'Together for the Future: activities in education, sports, and holistic development.',
      'Robô em uma estação de trabalho tecnológica': 'Robot at a technology workstation',
    'R$ 16 mi': 'R$ 16 million', 'R$ 16 milhões': 'R$ 16 million', 'R$ 4,40 milhões': 'R$ 4.40 million', 'R$ 4,05 milhões': 'R$ 4.05 million', 'R$ 3,65 milhões': 'R$ 3.65 million', 'R$ 1,35 milhão': 'R$ 1.35 million', 'R$ 1,45 milhão': 'R$ 1.45 million', 'R$ 1,10 milhão': 'R$ 1.10 million',
  'OMEGA TECH COMUNIDADE | Instituto Kátia Carvalho': 'OMEGA TECH COMUNIDADE | Instituto Kátia Carvalho',
  'Juntos pelo futuro | Instituto Kátia Carvalho': 'Together for the Future | Instituto Kátia Carvalho',
  'Inclusão digital, tecnologia e desenvolvimento comunitário.': 'Digital inclusion, technology, and community development.',
  'Inclusão digital, formação tecnológica e desenvolvimento comunitário.': 'Digital inclusion, technology training, and community development.',
  'Iniciativas que conectam cuidado, oportunidade e transformação social.': 'Initiatives connecting care, opportunity, and social change.',
  'Programa Integrado de Inclusão Digital, Tecnologia, IA, Empreendedorismo e Desenvolvimento Comunitário.': 'Integrated Program for Digital Inclusion, Technology, AI, Entrepreneurship, and Community Development.',
  'Quero Apoiar': 'Support us',
  'Atividades de educação, esporte e desenvolvimento integral.': 'Activities in education, sports, and holistic development.',
  'Tecnologia para o desenvolvimento local': 'Technology for local development',
  'Empregabilidade e empreendedorismo.': 'Employability and entrepreneurship.',
  ', sujeita a estudo preliminar, projeto legal e disponibilidade do imóvel.': ', subject to preliminary studies, permitting, and property availability.',
  'Entre em contato': 'Get in touch',
  'Programa Integrado de Inclusão Digital, Tecnologia, IA, Empreendedorismo e Desenvolvimento Comunitário': 'Integrated Program for Digital Inclusion, Technology, AI, Entrepreneurship, and Community Development',
  'Infraestrutura comunitária para ampliar oportunidades por meio de tecnologia, formação, inovação e geração de renda.': 'Community infrastructure to expand opportunities through technology, learning, innovation, and income generation.',
  'Fale sobre o projeto': 'Discuss the project', 'Ver metas e orçamento': 'View targets and budget',
  'Números do projeto': 'Project figures', 'Beneficiários diretos': 'Direct beneficiaries', 'Investimento total': 'Total investment', '24 meses': '24 months', 'Duração prevista': 'Planned duration', 'Trilhas de formação e empregabilidade': 'Training and employability pathways',
  'Sobre o projeto': 'About the project', 'Tecnologia, aprendizagem e geração de renda conectadas à comunidade.': 'Technology, learning, and income generation connected to the community.',
  'O OMEGA TECH COMUNIDADE integra infraestrutura, aprendizagem e geração de renda, combinando acesso à tecnologia, formação profissional, inovação, empregabilidade, empreendedorismo e desenvolvimento comunitário.': 'OMEGA TECH COMUNIDADE integrates infrastructure, learning, and income generation, combining access to technology, professional training, innovation, employability, entrepreneurship, and community development.',
  'O projeto busca transformar infraestrutura em capacidades, capacidades em oportunidades e oportunidades em desenvolvimento local.': 'The project aims to turn infrastructure into capabilities, capabilities into opportunities, and opportunities into local development.',
  'Inclusão digital': 'Digital inclusion', 'Formação profissional': 'Professional training', 'Robótica e fabricação digital': 'Robotics and digital fabrication', 'Inteligência Artificial e software': 'Artificial intelligence and software', 'Empregabilidade e empreendedorismo': 'Employability and entrepreneurship', 'Marketing digital e finanças': 'Digital marketing and finance', 'Desenvolvimento comunitário': 'Community development',
  'Contexto': 'Context', 'Desafios que orientam a proposta': 'Challenges that shape the proposal', 'Principais desafios identificados no projeto executivo.': 'Main challenges identified in the project plan.', 'Acesso': 'Access', 'Equipamentos, conectividade e ambientes adequados ainda são insuficientes para parcelas relevantes da população.': 'Equipment, connectivity, and suitable spaces remain insufficient for significant parts of the population.', 'Competências': 'Skills', 'O uso cotidiano do celular não substitui competências digitais, profissionais e de segurança.': 'Everyday mobile phone use does not replace digital, professional, and safety skills.', 'Oportunidade': 'Opportunity', 'Empresas demandam habilidades digitais enquanto jovens e adultos enfrentam barreiras de entrada.': 'Companies need digital skills while young people and adults face barriers to entry.',
  'Objetivo geral': 'Overall objective', 'Promover transformação social e econômica por meio de acesso, qualificação tecnológica e conexão com oportunidades.': 'Promote social and economic transformation through access, technology training, and connections to opportunities.', 'Objetivos específicos': 'Specific objectives', 'Capacidade que permanece no território.': 'Building capacity that stays in the community.', 'Implantar o centro;': 'Establish the center;', 'Formar beneficiários;': 'Train beneficiaries;', 'Apoiar projetos e negócios;': 'Support projects and businesses;', 'Conectar talentos ao mercado;': 'Connect talent with the job market;', 'Criar capacidade local sustentável.': 'Build sustainable local capacity.',
  'Público-alvo': 'Target groups', 'Prioridades de participação previstas': 'Planned participation priorities', 'Jovens de 14 a 29 anos': 'Young people aged 14 to 29', 'Adultos em transição profissional': 'Adults in career transition', 'Mulheres e grupos sub-representados': 'Women and underrepresented groups', 'Educadores e lideranças': 'Educators and community leaders', 'Pessoas 60+': 'People aged 60+',
  'Estrutura do programa': 'Program structure', 'Cinco frentes integradas': 'Five integrated areas', 'INCLUSÃO': 'INCLUSION', 'Acesso assistido e cidadania digital.': 'Supported access and digital citizenship.', 'FORMAÇÃO': 'TRAINING', 'Cursos modulares por competência.': 'Competency-based modular courses.', 'INOVAÇÃO': 'INNOVATION', 'Robótica, fabricação digital e IA.': 'Robotics, digital fabrication, and AI.', 'TRABALHO': 'WORK', 'COMUNIDADE': 'COMMUNITY', 'Rede local e uso compartilhado.': 'Local network and shared use.',
  'Estrutura física': 'Physical facilities', 'Um centro para aprender, produzir e conviver.': 'A center for learning, making, and connecting.', 'A área de referência prevista é de aproximadamente': 'The planned reference area is approximately', 'sujeita a estudo preliminar, projeto legal e disponibilidade do imóvel.': 'subject to preliminary studies, permitting, and property availability.', '4 salas flexíveis e laboratório de informática;': '4 flexible classrooms and a computer lab;', 'Espaços de robótica, eletrônica e impressão 3D;': 'Robotics, electronics, and 3D printing spaces;', 'IA, desenvolvimento de software e coworking;': 'AI, software development, and coworking;', 'Recepção, administração, acessibilidade e convivência.': 'Reception, administration, accessibility, and shared spaces.',
  'Ambientes de aprendizagem': 'Learning environments', 'Espaços especializados por prática': 'Practice-based specialist spaces', 'DIGITAL': 'DIGITAL', 'Informática, produtividade e cidadania.': 'Computing, productivity, and citizenship.', 'SOFTWARE & IA': 'SOFTWARE & AI', 'Programação, dados e inteligência artificial.': 'Programming, data, and artificial intelligence.', 'ROBÓTICA': 'ROBOTICS', 'Eletrônica, automação e prototipagem.': 'Electronics, automation, and prototyping.', 'FAB LAB': 'FAB LAB', 'Modelagem, fabricação e impressão 3D.': 'Modeling, fabrication, and 3D printing.', 'Equipamentos previstos': 'Planned equipment', 'computadores e periféricos': 'computers and peripherals', 'notebooks': 'laptops', 'kits de robótica': 'robotics kits', 'impressoras 3D': '3D printers', 'conjuntos de rede, servidores e audiovisual': 'networking, server, and audiovisual sets',
  'Formação e empregabilidade': 'Training and employability', 'Trilhas para desenvolver competências': 'Pathways to build skills', 'O programa contempla 10 trilhas; as áreas principais incluem:': 'The program includes 10 pathways; the main areas include:', 'BASE DIGITAL': 'DIGITAL FOUNDATIONS', 'Informática, produtividade, segurança e cidadania.': 'Computing, productivity, safety, and citizenship.', 'TECNOLOGIA': 'TECHNOLOGY', 'Programação, web, dados e inteligência artificial.': 'Programming, web, data, and artificial intelligence.', 'INDÚSTRIA 4.0': 'INDUSTRY 4.0', 'Robótica, automação, modelagem e impressão 3D.': 'Robotics, automation, modeling, and 3D printing.', 'RENDA': 'INCOME', 'Empreendedorismo, marketing digital, finanças e carreira.': 'Entrepreneurship, digital marketing, finance, and careers.',
  'Jornada do beneficiário': 'Participant journey', 'Da inscrição à próxima oportunidade': 'From enrollment to the next opportunity', 'INSCRIÇÃO': 'ENROLLMENT', 'Busca ativa e critérios públicos.': 'Active outreach and public criteria.', 'DIAGNÓSTICO': 'ASSESSMENT', 'Perfil e trilha indicada.': 'Profile and recommended pathway.', 'FORMAÇÃO': 'TRAINING', 'Aulas e prática supervisionada.': 'Classes and supervised practice.', 'PORTFÓLIO': 'PORTFOLIO', 'Projeto aplicado.': 'Applied project.', 'SAÍDA': 'NEXT STEP', 'Emprego, negócio ou continuidade.': 'Employment, a business, or continued learning.',
  'Metas e impacto': 'Targets and impact', 'Resultados previstos': 'Planned results', 'beneficiários diretos': 'direct beneficiaries', 'certificações em cursos': 'course certifications', 'atendimentos de inclusão digital': 'digital inclusion service visits', 'projetos e mentorias': 'projects and mentoring engagements', 'bolsas e apoios': 'scholarships and support grants', 'Meta de inserção produtiva acompanhada.': 'Target for tracked entry into employment or income-generating activity.', 'Acompanhamento de indicadores': 'Performance monitoring', 'O projeto prevê monitoramento de metas e resultados, painel de indicadores, reporte trimestral e prestação de contas.': 'The project plans to monitor targets and results through a performance dashboard, quarterly reporting, and financial accountability.',
  'Cronograma': 'Timeline', 'Implantação em cinco períodos': 'Implementation in five periods', 'Projetos, licenças e governança': 'Design, permits, and governance', 'Obras e aquisições críticas': 'Construction and critical procurement', 'Instalação e contratação': 'Installation and hiring', 'Operação assistida': 'Supported operations', 'Escala e consolidação': 'Scaling and consolidation',
  'Transparência financeira': 'Financial transparency', 'Orçamento previsto': 'Planned budget', 'Investimento total do projeto:': 'Total project investment:', 'Obras e adequações': 'Construction and fit-out', 'Equipamentos e tecnologia': 'Equipment and technology', 'Equipe técnica e bolsas': 'Technical team and scholarships', 'Software, IA e conteúdo': 'Software, AI, and content', 'Gestão, comunicação e auditoria': 'Management, communications, and audit', 'Reserva técnica': 'Contingency reserve', 'Total': 'Total',
  'Governança e transparência': 'Governance and transparency', 'Gestão, controle e prestação de contas': 'Management, controls, and accountability', 'O projeto prevê trilha documental, conciliação mensal, reporte trimestral, painel de indicadores e auditoria independente.': 'The project plans documented records, monthly reconciliation, quarterly reporting, a performance dashboard, and independent auditing.', 'Comitê estratégico': 'Strategic committee', 'Unidade gestora': 'Management unit', 'Coordenação técnica': 'Technical coordination', 'Controle e transparência': 'Controls and transparency', 'Auditoria': 'Audit', 'Prestação de contas': 'Financial accountability', 'Monitoramento de indicadores': 'Performance monitoring', 'Impacto social': 'Social impact', 'Infraestrutura que se converte em capacidade e oportunidade local.': 'Infrastructure that builds local capacity and opportunity.', 'Conheça mais sobre o OMEGA TECH COMUNIDADE e as possibilidades de parceria.': 'Learn more about OMEGA TECH COMUNIDADE and partnership opportunities.',
  'Dados bancários copiados.': 'Bank details copied.', 'Copiar dados bancários': 'Copy bank details', 'Faça uma doação': 'Make a donation', 'Ajude o Instituto Kátia Carvalho a ampliar suas ações e projetos sociais. Sua contribuição pode ajudar a transformar oportunidades em impacto social.': 'Help Instituto Kátia Carvalho expand its social actions and projects. Your contribution can help turn opportunities into social impact.', 'Banco': 'Bank', 'Agência': 'Branch', 'Conta': 'Account', 'Titular': 'Account holder', 'WhatsApp': 'WhatsApp', '+55 31 9168-5374': '+55 31 9168-5374', 'Apoie nossas ações': 'Support our work', 'Fale com o Instituto': 'Contact the Institute', 'Estamos à disposição.': 'We are here to help.', 'E-mail': 'Email',
  'Projetos em movimento': 'Projects in action', 'Conheça os projetos do Instituto Kátia Carvalho.': 'Explore Instituto Kátia Carvalho projects.', 'Tecnologia e desenvolvimento comunitário': 'Technology and community development', 'Saiba mais': 'Learn more', 'Juntos pelo futuro': 'Together for the Future', 'Atividades que conectam educação, esporte e desenvolvimento integral para crianças e adolescentes.': 'Activities connecting education, sports, and holistic development for children and teens.', 'Informações disponíveis': 'Available information', 'Educação, esporte e desenvolvimento integral.': 'Education, sports, and holistic development.', 'O projeto Juntos pelo futuro promove atividades que conectam educação, esporte e desenvolvimento integral para crianças e adolescentes.': 'The Together for the Future project offers activities connecting education, sports, and holistic development for children and teens.', 'Conheça o projeto': 'Learn about the project', 'Para conversar sobre o projeto, entre em contato com o Instituto Kátia Carvalho.': 'To discuss the project, contact Instituto Kátia Carvalho.', 'Voltar a Projetos': 'Back to Projects', 'Conheça também: OMEGA TECH COMUNIDADE': 'Also explore: OMEGA TECH COMUNIDADE', 'Projetos': 'Projects', 'Início': 'Home', 'O Instituto': 'About Us', 'Transparência': 'Transparency', 'Voluntariado': 'Volunteer', 'Contato': 'Contact', 'Quero apoiar': 'Support us', 'Impacto social': 'Social impact', 'Solidariedade, inclusão e desenvolvimento comunitário.': 'Solidarity, inclusion, and community development.', 'Links rápidos': 'Quick links', 'Redes sociais': 'Social media', 'Política de privacidade': 'Privacy policy', 'Navegação principal': 'Main navigation', 'Instituto Kátia Carvalho, início': 'Instituto Kátia Carvalho, home', '© Instituto Kátia Carvalho – Todos os direitos reservados': '© Instituto Kátia Carvalho. All rights reserved.'
});

Object.assign(translations.es, {
        '/ Juntos pelo futuro': '/ Juntos por el futuro',
      'OMEGA TECH COMUNIDADE: inclusão digital, tecnologia e desenvolvimento comunitário.': 'OMEGA TECH COMUNIDADE: inclusión digital, tecnología y desarrollo comunitario.',
      'Juntos pelo futuro: atividades de educação, esporte e desenvolvimento integral.': 'Juntos por el futuro: actividades de educación, deporte y desarrollo integral.',
      'Robô em uma estação de trabalho tecnológica': 'Robot en una estación de trabajo tecnológica',
    'R$ 16 mi': 'R$ 16 millones', 'R$ 16 milhões': 'R$ 16 millones', 'R$ 4,40 milhões': 'R$ 4,40 millones', 'R$ 4,05 milhões': 'R$ 4,05 millones', 'R$ 3,65 milhões': 'R$ 3,65 millones', 'R$ 1,35 milhão': 'R$ 1,35 millones', 'R$ 1,45 milhão': 'R$ 1,45 millones', 'R$ 1,10 milhão': 'R$ 1,10 millones',
  'OMEGA TECH COMUNIDADE | Instituto Kátia Carvalho': 'OMEGA TECH COMUNIDADE | Instituto Kátia Carvalho',
  'Juntos pelo futuro | Instituto Kátia Carvalho': 'Juntos por el futuro | Instituto Kátia Carvalho',
  'Inclusão digital, tecnologia e desenvolvimento comunitário.': 'Inclusión digital, tecnología y desarrollo comunitario.',
  'Inclusão digital, formação tecnológica e desenvolvimento comunitário.': 'Inclusión digital, formación tecnológica y desarrollo comunitario.',
  'Iniciativas que conectam cuidado, oportunidade e transformação social.': 'Iniciativas que conectan cuidado, oportunidades y transformación social.',
  'Programa Integrado de Inclusão Digital, Tecnologia, IA, Empreendedorismo e Desenvolvimento Comunitário.': 'Programa Integrado de Inclusión Digital, Tecnología, IA, Emprendimiento y Desarrollo Comunitario.',
  'Quero Apoiar': 'Quiero apoyar',
  'Atividades de educação, esporte e desenvolvimento integral.': 'Actividades de educación, deporte y desarrollo integral.',
  'Tecnologia para o desenvolvimento local': 'Tecnología para el desarrollo local',
  'Empregabilidade e empreendedorismo.': 'Empleabilidad y emprendimiento.',
  ', sujeita a estudo preliminar, projeto legal e disponibilidade do imóvel.': ', sujeta a estudio preliminar, proyecto legal y disponibilidad del inmueble.',
  'Entre em contato': 'Póngase en contacto',
  'Programa Integrado de Inclusão Digital, Tecnologia, IA, Empreendedorismo e Desenvolvimento Comunitário': 'Programa Integrado de Inclusión Digital, Tecnología, IA, Emprendimiento y Desarrollo Comunitario',
  'Infraestrutura comunitária para ampliar oportunidades por meio de tecnologia, formação, inovação e geração de renda.': 'Infraestructura comunitaria para ampliar oportunidades mediante tecnología, formación, innovación y generación de ingresos.',
  'Fale sobre o projeto': 'Hablemos del proyecto', 'Ver metas e orçamento': 'Ver metas y presupuesto', 'Números do projeto': 'Cifras del proyecto', 'Beneficiários diretos': 'Beneficiarios directos', 'Investimento total': 'Inversión total', '24 meses': '24 meses', 'Duração prevista': 'Duración prevista', 'Trilhas de formação e empregabilidade': 'Rutas de formación y empleabilidad',
  'Sobre o projeto': 'Sobre el proyecto', 'Tecnologia, aprendizagem e geração de renda conectadas à comunidade.': 'Tecnología, aprendizaje y generación de ingresos conectados con la comunidad.',
  'O OMEGA TECH COMUNIDADE integra infraestrutura, aprendizagem e geração de renda, combinando acesso à tecnologia, formação profissional, inovação, empregabilidade, empreendedorismo e desenvolvimento comunitário.': 'OMEGA TECH COMUNIDADE integra infraestructura, aprendizaje y generación de ingresos, combinando acceso a la tecnología, formación profesional, innovación, empleabilidad, emprendimiento y desarrollo comunitario.', 'O projeto busca transformar infraestrutura em capacidades, capacidades em oportunidades e oportunidades em desenvolvimento local.': 'El proyecto busca transformar infraestructura en capacidades, capacidades en oportunidades y oportunidades en desarrollo local.',
  'Inclusão digital': 'Inclusión digital', 'Formação profissional': 'Formación profesional', 'Robótica e fabricação digital': 'Robótica y fabricación digital', 'Inteligência Artificial e software': 'Inteligencia artificial y software', 'Empregabilidade e empreendedorismo': 'Empleabilidad y emprendimiento', 'Marketing digital e finanças': 'Marketing digital y finanzas', 'Desenvolvimento comunitário': 'Desarrollo comunitario',
  'Contexto': 'Contexto', 'Desafios que orientam a proposta': 'Desafíos que orientan la propuesta', 'Principais desafios identificados no projeto executivo.': 'Principales desafíos identificados en el proyecto ejecutivo.', 'Acesso': 'Acceso', 'Equipamentos, conectividade e ambientes adequados ainda são insuficientes para parcelas relevantes da população.': 'Los equipos, la conectividad y los espacios adecuados siguen siendo insuficientes para sectores importantes de la población.', 'Competências': 'Competencias', 'O uso cotidiano do celular não substitui competências digitais, profissionais e de segurança.': 'El uso cotidiano del celular no sustituye las competencias digitales, profesionales y de seguridad.', 'Oportunidade': 'Oportunidad', 'Empresas demandam habilidades digitais enquanto jovens e adultos enfrentam barreiras de entrada.': 'Las empresas demandan habilidades digitales mientras jóvenes y adultos enfrentan barreras de acceso.',
  'Objetivo geral': 'Objetivo general', 'Promover transformação social e econômica por meio de acesso, qualificação tecnológica e conexão com oportunidades.': 'Promover la transformación social y económica mediante el acceso, la capacitación tecnológica y la conexión con oportunidades.', 'Objetivos específicos': 'Objetivos específicos', 'Capacidade que permanece no território.': 'Capacidad que permanece en el territorio.', 'Implantar o centro;': 'Implementar el centro;', 'Formar beneficiários;': 'Formar a las personas beneficiarias;', 'Apoiar projetos e negócios;': 'Apoyar proyectos y negocios;', 'Conectar talentos ao mercado;': 'Conectar talentos con el mercado;', 'Criar capacidade local sustentável.': 'Crear capacidad local sostenible.',
  'Público-alvo': 'Público objetivo', 'Prioridades de participação previstas': 'Prioridades de participación previstas', 'Jovens de 14 a 29 anos': 'Jóvenes de 14 a 29 años', 'Adultos em transição profissional': 'Adultos en transición profesional', 'Mulheres e grupos sub-representados': 'Mujeres y grupos subrepresentados', 'Educadores e lideranças': 'Educadores y líderes comunitarios', 'Pessoas 60+': 'Personas de 60 años o más',
  'Estrutura do programa': 'Estructura del programa', 'Cinco frentes integradas': 'Cinco áreas integradas', 'INCLUSÃO': 'INCLUSIÓN', 'Acesso assistido e cidadania digital.': 'Acceso asistido y ciudadanía digital.', 'FORMAÇÃO': 'FORMACIÓN', 'Cursos modulares por competência.': 'Cursos modulares por competencias.', 'INOVAÇÃO': 'INNOVACIÓN', 'Robótica, fabricação digital e IA.': 'Robótica, fabricación digital e IA.', 'TRABALHO': 'TRABAJO', 'Empregabilidade e empreendedorismo.': 'Empleabilidad y emprendimiento.', 'COMUNIDADE': 'COMUNIDAD', 'Rede local e uso compartilhado.': 'Red local y uso compartido.',
  'Estrutura física': 'Infraestructura física', 'Um centro para aprender, produzir e conviver.': 'Un centro para aprender, producir y convivir.', 'A área de referência prevista é de aproximadamente': 'El área de referencia prevista es de aproximadamente', 'sujeita a estudo preliminar, projeto legal e disponibilidade do imóvel.': 'sujeta a estudio preliminar, proyecto legal y disponibilidad del inmueble.', '4 salas flexíveis e laboratório de informática;': '4 salas flexibles y laboratorio de informática;', 'Espaços de robótica, eletrônica e impressão 3D;': 'Espacios de robótica, electrónica e impresión 3D;', 'IA, desenvolvimento de software e coworking;': 'IA, desarrollo de software y coworking;', 'Recepção, administração, acessibilidade e convivência.': 'Recepción, administración, accesibilidad y convivencia.',
  'Ambientes de aprendizagem': 'Espacios de aprendizaje', 'Espaços especializados por prática': 'Espacios especializados por práctica', 'DIGITAL': 'DIGITAL', 'Informática, produtividade e cidadania.': 'Informática, productividad y ciudadanía.', 'SOFTWARE & IA': 'SOFTWARE E IA', 'Programação, dados e inteligência artificial.': 'Programación, datos e inteligencia artificial.', 'ROBÓTICA': 'ROBÓTICA', 'Eletrônica, automação e prototipagem.': 'Electrónica, automatización y prototipado.', 'FAB LAB': 'FAB LAB', 'Modelagem, fabricação e impressão 3D.': 'Modelado, fabricación e impresión 3D.', 'Equipamentos previstos': 'Equipos previstos', 'computadores e periféricos': 'computadoras y periféricos', 'notebooks': 'portátiles', 'kits de robótica': 'kits de robótica', 'impressoras 3D': 'impresoras 3D', 'conjuntos de rede, servidores e audiovisual': 'conjuntos de redes, servidores y equipos audiovisuales',
  'Formação e empregabilidade': 'Formación y empleabilidad', 'Trilhas para desenvolver competências': 'Rutas para desarrollar competencias', 'O programa contempla 10 trilhas; as áreas principais incluem:': 'El programa contempla 10 rutas; las principales áreas incluyen:', 'BASE DIGITAL': 'BASE DIGITAL', 'Informática, produtividade, segurança e cidadania.': 'Informática, productividad, seguridad y ciudadanía.', 'TECNOLOGIA': 'TECNOLOGÍA', 'Programação, web, dados e inteligência artificial.': 'Programación, web, datos e inteligencia artificial.', 'INDÚSTRIA 4.0': 'INDUSTRIA 4.0', 'Robótica, automação, modelagem e impressão 3D.': 'Robótica, automatización, modelado e impresión 3D.', 'RENDA': 'INGRESOS', 'Empreendedorismo, marketing digital, finanças e carreira.': 'Emprendimiento, marketing digital, finanzas y carrera profesional.',
  'Jornada do beneficiário': 'Recorrido de la persona beneficiaria', 'Da inscrição à próxima oportunidade': 'De la inscripción a la próxima oportunidad', 'INSCRIÇÃO': 'INSCRIPCIÓN', 'Busca ativa e critérios públicos.': 'Búsqueda activa y criterios públicos.', 'DIAGNÓSTICO': 'DIAGNÓSTICO', 'Perfil e trilha indicada.': 'Perfil y ruta recomendada.', 'FORMAÇÃO': 'FORMACIÓN', 'Aulas e prática supervisionada.': 'Clases y práctica supervisada.', 'PORTFÓLIO': 'PORTAFOLIO', 'Projeto aplicado.': 'Proyecto aplicado.', 'SAÍDA': 'SALIDA', 'Emprego, negócio ou continuidade.': 'Empleo, negocio o continuidad formativa.',
  'Metas e impacto': 'Metas e impacto', 'Resultados previstos': 'Resultados previstos', 'beneficiários diretos': 'beneficiarios directos', 'certificações em cursos': 'certificaciones en cursos', 'atendimentos de inclusão digital': 'atenciones de inclusión digital', 'projetos e mentorias': 'proyectos y mentorías', 'bolsas e apoios': 'becas y apoyos', 'Meta de inserção produtiva acompanhada.': 'Meta de inserción productiva con seguimiento.', 'Acompanhamento de indicadores': 'Seguimiento de indicadores', 'O projeto prevê monitoramento de metas e resultados, painel de indicadores, reporte trimestral e prestação de contas.': 'El proyecto prevé el seguimiento de metas y resultados, un panel de indicadores, informes trimestrales y rendición de cuentas.',
  'Cronograma': 'Cronograma', 'Implantação em cinco períodos': 'Implementación en cinco períodos', 'Projetos, licenças e governança': 'Proyectos, permisos y gobernanza', 'Obras e aquisições críticas': 'Obras y adquisiciones críticas', 'Instalação e contratação': 'Instalación y contratación', 'Operação assistida': 'Operación asistida', 'Escala e consolidação': 'Escala y consolidación',
  'Transparência financeira': 'Transparencia financiera', 'Orçamento previsto': 'Presupuesto previsto', 'Investimento total do projeto:': 'Inversión total del proyecto:', 'Obras e adequações': 'Obras y adecuaciones', 'Equipamentos e tecnologia': 'Equipos y tecnología', 'Equipe técnica e bolsas': 'Equipo técnico y becas', 'Software, IA e conteúdo': 'Software, IA y contenidos', 'Gestão, comunicação e auditoria': 'Gestión, comunicación y auditoría', 'Reserva técnica': 'Reserva técnica', 'Total': 'Total',
  'Governança e transparência': 'Gobernanza y transparencia', 'Gestão, controle e prestação de contas': 'Gestión, control y rendición de cuentas', 'O projeto prevê trilha documental, conciliação mensal, reporte trimestral, painel de indicadores e auditoria independente.': 'El proyecto prevé documentación, conciliación mensual, informes trimestrales, un panel de indicadores y auditoría independiente.', 'Comitê estratégico': 'Comité estratégico', 'Unidade gestora': 'Unidad gestora', 'Coordenação técnica': 'Coordinación técnica', 'Controle e transparência': 'Control y transparencia', 'Auditoria': 'Auditoría', 'Prestação de contas': 'Rendición de cuentas', 'Monitoramento de indicadores': 'Seguimiento de indicadores', 'Impacto social': 'Impacto social', 'Infraestrutura que se converte em capacidade e oportunidade local.': 'Infraestructura que se convierte en capacidad y oportunidad local.', 'Conheça mais sobre o OMEGA TECH COMUNIDADE e as possibilidades de parceria.': 'Conozca más sobre OMEGA TECH COMUNIDADE y las posibilidades de colaboración.',
  'Dados bancários copiados.': 'Datos bancarios copiados.', 'Copiar dados bancários': 'Copiar datos bancarios', 'Faça uma doação': 'Haga una donación', 'Ajude o Instituto Kátia Carvalho a ampliar suas ações e projetos sociais. Sua contribuição pode ajudar a transformar oportunidades em impacto social.': 'Ayude al Instituto Kátia Carvalho a ampliar sus acciones y proyectos sociales. Su contribución puede convertir oportunidades en impacto social.', 'Banco': 'Banco', 'Agência': 'Sucursal', 'Conta': 'Cuenta', 'Titular': 'Titular', 'WhatsApp': 'WhatsApp', '+55 31 9168-5374': '+55 31 9168-5374', 'Apoie nossas ações': 'Apoye nuestras acciones', 'Fale com o Instituto': 'Hable con el Instituto', 'Estamos à disposição.': 'Estamos a su disposición.', 'E-mail': 'Correo electrónico',
  'Projetos em movimento': 'Proyectos en marcha', 'Conheça os projetos do Instituto Kátia Carvalho.': 'Conozca los proyectos del Instituto Kátia Carvalho.', 'Tecnologia e desenvolvimento comunitário': 'Tecnología y desarrollo comunitario', 'Saiba mais': 'Más información', 'Juntos pelo futuro': 'Juntos por el futuro', 'Atividades que conectam educação, esporte e desenvolvimento integral para crianças e adolescentes.': 'Actividades que conectan la educación, el deporte y el desarrollo integral para niños, niñas y adolescentes.', 'Informações disponíveis': 'Información disponible', 'Educação, esporte e desenvolvimento integral.': 'Educación, deporte y desarrollo integral.', 'O projeto Juntos pelo futuro promove atividades que conectam educação, esporte e desenvolvimento integral para crianças e adolescentes.': 'El proyecto Juntos por el futuro ofrece actividades que conectan la educación, el deporte y el desarrollo integral para niños, niñas y adolescentes.', 'Conheça o projeto': 'Conozca el proyecto', 'Para conversar sobre o projeto, entre em contato com o Instituto Kátia Carvalho.': 'Para conversar sobre el proyecto, póngase en contacto con el Instituto Kátia Carvalho.', 'Voltar a Projetos': 'Volver a Proyectos', 'Conheça também: OMEGA TECH COMUNIDADE': 'Conozca también: OMEGA TECH COMUNIDADE', 'Projetos': 'Proyectos', 'Início': 'Inicio', 'O Instituto': 'El Instituto', 'Transparência': 'Transparencia', 'Voluntariado': 'Voluntariado', 'Contato': 'Contacto', 'Quero apoiar': 'Quiero apoyar', 'Impacto social': 'Impacto social', 'Solidariedade, inclusão e desenvolvimento comunitário.': 'Solidaridad, inclusión y desarrollo comunitario.', 'Links rápidos': 'Enlaces rápidos', 'Redes sociais': 'Redes sociales', 'Política de privacidade': 'Política de privacidad', 'Navegação principal': 'Navegación principal', 'Instituto Kátia Carvalho, início': 'Inicio del Instituto Kátia Carvalho', '© Instituto Kátia Carvalho – Todos os direitos reservados': '© Instituto Kátia Carvalho. Todos los derechos reservados.'
});

(() => {
  const languages = ['pt', 'en', 'es'];
  const locale = { pt: 'pt-BR', en: 'en', es: 'es' };
  const currentPath = window.location.pathname.toLowerCase();
  const currentFile = currentPath.split('/').pop() || 'index.html';
  const isOnePageSite = currentFile === 'site-institucional.html';
  const isProjectDetail = currentPath.includes('/projetos/omega-tech-comunidade/') || currentPath.includes('/projetos/juntos-pelo-futuro/');
  const activeNavFile = isProjectDetail ? 'projetos.html' : currentFile;
  const pageKey = currentPath.includes('/projetos/omega-tech-comunidade/') ? 'omega'
    : currentPath.includes('/projetos/juntos-pelo-futuro/') ? 'juntos'
    : isOnePageSite ? 'home-alt'
    : ({ 'instituto.html': 'about', 'projetos.html': 'projects', 'transparencia.html': 'transparency', 'voluntariado.html': 'volunteer', 'contato.html': 'contact' }[currentFile] || 'home');
  document.body.dataset.page = pageKey;
  const languageNames = {
    pt: { pt: 'PT-BR', en: 'PT-BR', es: 'PT-BR' },
    en: { pt: 'US-EN', en: 'US-EN', es: 'US-EN' },
    es: { pt: 'ES-ES', en: 'ES-ES', es: 'ES-ES' }
  };
  const originalTextNodes = [];
  const originalAttributes = [];
  const pageTitle = document.title;
  const description = document.querySelector('meta[name="description"]');
  const originalDescription = description?.content;
  const attributeNames = ['aria-label', 'alt', 'title', 'placeholder'];
  const nodeWalker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let textNode;

  while ((textNode = nodeWalker.nextNode())) {
    if (textNode.nodeValue.trim()) originalTextNodes.push({ node: textNode, source: textNode.nodeValue });
  }

  document.querySelectorAll('*').forEach((element) => {
    attributeNames.forEach((name) => {
      if (element.hasAttribute(name)) originalAttributes.push({ element, name, source: element.getAttribute(name) });
    });
  });

  const selector = document.createElement('select');
  selector.className = 'language-select';
  selector.setAttribute('aria-label', 'Idioma / Language / Idioma');
  selector.id = 'language-select';
  document.querySelector('.nav-wrap')?.append(selector);

  function updateLanguageOptions(language) {
    selector.setAttribute('aria-label', language === 'en' ? 'Choose language' : language === 'es' ? 'Elegir idioma' : 'Escolher idioma');
    selector.replaceChildren(...languages.map((code) => {
      const option = document.createElement('option');
      option.value = code;
      option.textContent = languageNames[code][language];
      return option;
    }));
    selector.value = language;
  }

  function updateActiveNavigation() {
    const currentAnchor = window.location.hash || '#inicio';
    document.querySelectorAll('nav a[href]').forEach((link) => {
      const href = link.getAttribute('href');
      const isActive = isOnePageSite
        ? href === currentAnchor
        : !href.startsWith('#') && new URL(href, window.location.href).pathname.toLowerCase().endsWith(`/${activeNavFile}`);
      link.classList.toggle('is-active', isActive);
      if (isActive) link.setAttribute('aria-current', isOnePageSite ? 'location' : 'page');
      else link.removeAttribute('aria-current');
    });
  }

  function preserveLanguageInLinks(language) {
    document.querySelectorAll('a[href]').forEach((link) => {
      const href = link.getAttribute('href');
      if (!href || /^(https?:|mailto:|tel:|#)/i.test(href) || !/\.html(?:[?#]|$)/i.test(href)) return;
      const url = new URL(href, window.location.href);
      url.searchParams.set('lang', language);
      const relativePath = href.split(/[?#]/, 1)[0];
      link.setAttribute('href', `${relativePath}${url.search}${url.hash}`);
    });
  }

  function applyLanguage(language) {
    if (!languages.includes(language)) language = 'pt';
    const dictionary = translations[language];
    originalTextNodes.forEach(({ node, source }) => {
      const leading = source.match(/^\s*/)[0];
      const trailing = source.match(/\s*$/)[0];
      const key = source.trim();
      if (Object.hasOwn(dictionary, key)) node.nodeValue = `${leading}${dictionary[key]}${trailing}`;
    });
    originalAttributes.forEach(({ element, name, source }) => {
      if (Object.hasOwn(dictionary, source)) element.setAttribute(name, dictionary[source]);
    });
    if (Object.hasOwn(dictionary, pageTitle)) document.title = dictionary[pageTitle];
    if (description && originalDescription && Object.hasOwn(dictionary, originalDescription)) description.content = dictionary[originalDescription];
    document.documentElement.lang = locale[language];
    updateLanguageOptions(language);
    preserveLanguageInLinks(language);
    try { localStorage.setItem('ikc-language', language); } catch {}
  }

  const queryLanguage = new URLSearchParams(window.location.search).get('lang');
  let savedLanguage = 'pt';
  try { savedLanguage = localStorage.getItem('ikc-language') || 'pt'; } catch {}
  applyLanguage(languages.includes(queryLanguage) ? queryLanguage : savedLanguage);
  updateActiveNavigation();
  window.addEventListener('hashchange', updateActiveNavigation);
  selector.addEventListener('change', () => applyLanguage(selector.value));
})();